version: 0.1
# brent lemons 20200206

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew build
      - docker build -t $ECR_REPO_NAME:latest .
      - docker tag $ECR_REPO_NAME:latest $ECR_REPO_IMAGE_URL:latest
      - docker push $ECR_REPO_IMAGE_URL:latest
  post_build:
    commands:
      - aws cloudformation package --output-template-file outputtemplate.yaml --template-file template.yaml --s3-bucket bkl-test-starter

artifacts:
  files:
    - outputtemplate.yaml
  discard-paths: yes