AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create a new ECS Fargate First Run stack
Parameters:
  StreamJson:
    Description: Should kinesis messages be JSON formatted
    Type: String
    Default: 'true'
  StreamCompress:
    Description: Should kinesis messages be compressed
    Type: String
    Default: 'true'
  ECRRepositoryUri:
    Description: Where this pipeline should store built artifacts
    Type: String
  ECRImageTag:
    Description: Where this pipeline should store built artifacts
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.76.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-vpc'
        
  SwimSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified CIDR ranges
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: 10.76.3.0/24
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.76.3.0/24
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-public-subnet'

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-internet-gateway'

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  SwimIngestKinesisStreamSTDDS: 
    Type: AWS::Kinesis::Stream 
    Properties: 
      RetentionPeriodHours: 24
      ShardCount: 1

  SwimIngestKinesisStreamFDPS: 
    Type: AWS::Kinesis::Stream 
    Properties: 
      RetentionPeriodHours: 24 
      ShardCount: 1

  SwimIngestKinesisStreamTFMS: 
    Type: AWS::Kinesis::Stream 
    Properties: 
      RetentionPeriodHours: 24 
      ShardCount: 1

  SwimIngestECSServiceRoleSTDDS:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
      Path: /
      Policies:
        - PolicyName: ECSAccessParameters
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'ssm:GetParameters'
                Effect: Allow
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/swim/stdds*'
        - PolicyName: ECSWriteKinesis
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'kinesis:PutRecord'
                - 'kinesis:PutRecords'
                Effect: Allow
                Resource: !GetAtt SwimIngestKinesisStreamSTDDS.Arn

  SwimIngestECSServiceRoleFDPS:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
      Path: /
      Policies:
        - PolicyName: ECSAccessParameters
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'ssm:GetParameters'
                Effect: Allow
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/swim/fdps*'
        - PolicyName: ECSWriteKinesis
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'kinesis:PutRecord'
                - 'kinesis:PutRecords'
                Effect: Allow
                Resource: !GetAtt SwimIngestKinesisStreamFDPS.Arn

  SwimIngestECSServiceRoleTFMS:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
      Path: /
      Policies:
        - PolicyName: ECSAccessParameters
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'ssm:GetParameters'
                Effect: Allow
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/swim/tfms*'
        - PolicyName: ECSWriteKinesis
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'kinesis:PutRecord'
                - 'kinesis:PutRecords'
                Effect: Allow
                Resource: !GetAtt SwimIngestKinesisStreamTFMS.Arn

  SwimIngestECSCluster:
    Type: AWS::ECS::Cluster
    
  SwimIngestTaskDefinitionSTDDS:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      RequiresCompatibilities: 
        - 'FARGATE'
      ContainerDefinitions: 
        - Name: !Join ['-', [!Ref 'AWS::StackName', 'Container', 'STDDS']]
          Image: !Sub '${ECRRepositoryUri}:${ECRImageTag}'
          Essential: 'true'
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Sub '/ecs/${AWS::StackName}-stdds'
              awslogs-region: !Sub '${AWS::Region}'
              awslogs-stream-prefix: 'ecs'
          Environment:
            - Name: AWS_KINESIS_STREAM
              Value: !Ref SwimIngestKinesisStreamSTDDS
            - Name: AWS_KINESIS_STREAM_JSON
              Value: !Sub StreamJson
            - Name: AWS_KINESIS_STREAM_COMPRESS
              Value: !Sub StreamCompress
          Secrets:
            - Name: SWIM_JNDI_CONTEXT_FACTORY
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/stdds/smes/jndi/context_factory'
            - Name: SWIM_JNDI_HOST
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/stdds/smes/jndi/host'
            - Name: SWIM_JNDI_PRINCIPAL
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/stdds/smes/jndi/principal'
            - Name: SWIM_JNDI_CREDENTIALS
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/stdds/smes/jndi/credentials'
            - Name: SWIM_JNDI_VPN
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/stdds/smes/jndi/vpn'
            - Name: SWIM_JMS_CONNECTION_FACTORY_NAME
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/stdds/smes/jms/connection_factory_name'
            - Name: SWIM_JMS_QUEUE_NAME
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/stdds/smes/jms/queue_name'
      TaskRoleArn: !Ref SwimIngestECSServiceRoleSTDDS
      ExecutionRoleArn: !Ref SwimIngestECSServiceRoleSTDDS
      Memory: '1 GB'
      Cpu: '0.25 vCPU'
      Family: !Sub '${AWS::StackName}'
      NetworkMode: 'awsvpc'

  SwimIngestTaskDefinitionFDPS:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      RequiresCompatibilities: 
        - 'FARGATE'
      ContainerDefinitions: 
        - Name: !Join ['-', [!Ref 'AWS::StackName', 'Container', 'FDPS']]
          Image: !Sub '${ECRRepositoryUri}:${ECRImageTag}'
          Essential: 'true'
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Sub '/ecs/${AWS::StackName}-fdps'
              awslogs-region: !Sub '${AWS::Region}'
              awslogs-stream-prefix: 'ecs'
          Environment:
            - Name: AWS_KINESIS_STREAM
              Value: !Ref SwimIngestKinesisStreamFDPS
            - Name: AWS_KINESIS_STREAM_JSON
              Value: !Sub StreamJson
            - Name: AWS_KINESIS_STREAM_COMPRESS
              Value: !Sub StreamCompress
          Secrets:
            - Name: SWIM_JNDI_CONTEXT_FACTORY
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/fdps/jndi/context_factory'
            - Name: SWIM_JNDI_HOST
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/fdps/jndi/host'
            - Name: SWIM_JNDI_PRINCIPAL
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/fdps/jndi/principal'
            - Name: SWIM_JNDI_CREDENTIALS
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/fdps/jndi/credentials'
            - Name: SWIM_JNDI_VPN
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/fdps/jndi/vpn'
            - Name: SWIM_JMS_CONNECTION_FACTORY_NAME
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/fdps/jms/connection_factory_name'
            - Name: SWIM_JMS_QUEUE_NAME
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/fdps/jms/queue_name'
      TaskRoleArn: !Ref SwimIngestECSServiceRoleFDPS
      ExecutionRoleArn: !Ref SwimIngestECSServiceRoleFDPS
      Memory: '1 GB'
      Cpu: '0.25 vCPU'
      Family: !Sub '${AWS::StackName}'
      NetworkMode: 'awsvpc'

  SwimIngestTaskDefinitionTFMS:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      RequiresCompatibilities: 
        - 'FARGATE'
      ContainerDefinitions: 
        - Name: !Join ['-', [!Ref 'AWS::StackName', 'Container', 'TFMS']]
          Image: !Sub '${ECRRepositoryUri}:${ECRImageTag}'
          Essential: 'true'
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Sub '/ecs/${AWS::StackName}-tfms'
              awslogs-region: !Sub '${AWS::Region}'
              awslogs-stream-prefix: 'ecs'
          Environment:
            - Name: AWS_KINESIS_STREAM
              Value: !Ref SwimIngestKinesisStreamTFMS
            - Name: AWS_KINESIS_STREAM_JSON
              Value: !Sub StreamJson
            - Name: AWS_KINESIS_STREAM_COMPRESS
              Value: !Sub StreamCompress
          Secrets:
            - Name: SWIM_JNDI_CONTEXT_FACTORY
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/tfms/jndi/context_factory'
            - Name: SWIM_JNDI_HOST
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/tfms/jndi/host'
            - Name: SWIM_JNDI_PRINCIPAL
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/tfms/jndi/principal'
            - Name: SWIM_JNDI_CREDENTIALS
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/tfms/jndi/credentials'
            - Name: SWIM_JNDI_VPN
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/tfms/jndi/vpn'
            - Name: SWIM_JMS_CONNECTION_FACTORY_NAME
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/tfms/jms/connection_factory_name'
            - Name: SWIM_JMS_QUEUE_NAME
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/poc/swim/tfms/jms/queue_name'
      TaskRoleArn: !Ref SwimIngestECSServiceRoleTFMS
      ExecutionRoleArn: !Ref SwimIngestECSServiceRoleTFMS
      Memory: '1 GB'
      Cpu: '0.25 vCPU'
      Family: !Sub '${AWS::StackName}'
      NetworkMode: 'awsvpc'

  SwimIngestServiceSTDDS:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref SwimIngestECSCluster
      LaunchType: 'FARGATE'
      TaskDefinition: !Ref SwimIngestTaskDefinitionSTDDS
      ServiceName: !Sub 'swim-ingest-service-stdds'
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DeploymentController: 
        Type: 'ECS'
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: 'ENABLED'
          Subnets: 
            - !Ref PublicSubnet
          SecurityGroups: 
            - !Ref SwimSecurityGroup
            
  SwimIngestServiceFDPS:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref SwimIngestECSCluster
      LaunchType: 'FARGATE'
      TaskDefinition: !Ref SwimIngestTaskDefinitionFDPS
      ServiceName: !Sub 'swim-ingest-service-fdps'
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DeploymentController: 
        Type: 'ECS'
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: 'ENABLED'
          Subnets: 
            - !Ref PublicSubnet
          SecurityGroups: 
            - !Ref SwimSecurityGroup
            
  SwimIngestServiceTFMS:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref SwimIngestECSCluster
      LaunchType: 'FARGATE'
      TaskDefinition: !Ref SwimIngestTaskDefinitionTFMS
      ServiceName: !Sub 'swim-ingest-service-tfms'
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DeploymentController: 
        Type: 'ECS'
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: 'ENABLED'
          Subnets: 
            - !Ref PublicSubnet
          SecurityGroups: 
            - !Ref SwimSecurityGroup
            

Outputs:
  KinesisStreamSTDDS:
    Description: The kinesis stream to be consumed
    Value: !GetAtt SwimIngestKinesisStreamSTDDS.Arn 
    Export:
      Name: !Sub '${AWS::StackName}-KinesisStream-stdds'

  KinesisStreamFDPS:
    Description: The kinesis stream to be consumed
    Value: !GetAtt SwimIngestKinesisStreamFDPS.Arn 
    Export:
      Name: !Sub '${AWS::StackName}-KinesisStream-fdps'

  KinesisStreamTFMS:
    Description: The kinesis stream to be consumed
    Value: !GetAtt SwimIngestKinesisStreamTFMS.Arn 
    Export:
      Name: !Sub '${AWS::StackName}-KinesisStream-tfms'

