AWSTemplateFormatVersion: '2010-09-09'
Description: Template describing the service infrastructure
Resources:
  IamRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/bkl-swim-codepipeline/8843d6af1d0f902abe14e5b145e3a094.template
  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/bkl-swim-codepipeline/f3286bf9726c75bef51b952bab77f747.template
      Parameters:
        ArtifactBucketName:
          Fn::GetAtt:
          - IamRoles
          - Outputs.ArtifactBucketName
        CodePipelineServiceRoleArn:
          Fn::GetAtt:
          - IamRoles
          - Outputs.CodePipelineServiceRoleArn
        CodeBuildServiceRoleArn:
          Fn::GetAtt:
          - IamRoles
          - Outputs.CodeBuildServiceRoleArn
