AWSTemplateFormatVersion: '2010-09-09'
Description: Template describing the service infrastructure
Parameters:
  GitHubUsername:
    Type: String
    Description: Which branch to use.
  GitHubRepoName:
    Type: String
    Description: Which branch to use.
    Default: aws-swim-ingest-poc
  GitHubBranchName:
    Type: String
    Description: Which branch to use.
    Default: master
  GitHubToken:
    Type: String
    Description: Which branch to use.
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
  IamRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/bkl-swim-codepipeline/72de8b08ac623d71e82a136110512c54.template
      Parameters:
        ArtifactBucketName:
          Ref: ArtifactBucket
  ECRRepository:
    Type: AWS::ECR::Repository
  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/bkl-swim-codepipeline/e8019ac118e98ac5f5075a8a3be22c0c.template
      Parameters:
        ArtifactBucketName:
          Ref: ArtifactBucket
        ECRRepositoryName:
          Ref: ECRRepository
        CodePipelineServiceRoleArn:
          Fn::GetAtt:
          - IamRoles
          - Outputs.CodePipelineServiceRoleArn
        CodeBuildServiceRoleArn:
          Fn::GetAtt:
          - IamRoles
          - Outputs.CodeBuildServiceRoleArn
        GitHubUsername:
          Ref: GitHubUsername
        GitHubRepoName:
          Ref: GitHubRepoName
        GitHubBranchName:
          Ref: GitHubBranchName
        GitHubToken:
          Ref: GitHubToken
Outputs:
  ArtifactBucketName:
    Value:
      Ref: ArtifactBucket
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ArtifactBucketName
  ECRRepositoryName:
    Value:
      Ref: ECRRepository
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ECRRepositoryName
