AWSTemplateFormatVersion: '2010-09-09'
Description: Template describing the service infrastructure
Parameters:
  GitHubUsername:
    Type: String
    Description: Which branch to use.
  GitHubRepoName:
    Type: String
    Description: Which branch to use.
    Default: aws-swim-ingest-poc
  GitHubBranchName:
    Type: String
    Description: Which branch to use.
    Default: master
  GitHubToken:
    Type: String
    Description: Which branch to use.
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
  IamRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/bkl-swim-codepipeline/68ef40fdb9410df89b01b068294b9341.template
      Parameters:
        ArtifactBucketName:
          Ref: ArtifactBucket
  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/bkl-swim-codepipeline/6257395f15be6450a92567f33d82c33a.template
      Parameters:
        ArtifactBucketName:
          Ref: ArtifactBucket
        CodePipelineServiceRoleArn:
          Fn::GetAtt:
          - IamRoles
          - Outputs.CodePipelineServiceRoleArn
        CodeBuildServiceRoleArn:
          Fn::GetAtt:
          - IamRoles
          - Outputs.CodeBuildServiceRoleArn
        GitHubUsername:
          Ref: GitHubUsername
        GitHubRepoName:
          Ref: GitHubRepoName
        GitHubBranchName:
          Ref: GitHubBranchName
        GitHubToken:
          Ref: GitHubToken
Outputs:
  ArtifactBucketName:
    Value:
      Ref: ArtifactBucket
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ArtifactBucketName
