AWSTemplateFormatVersion: '2010-09-09'
Description: Template describing the service infrastructure
Parameters:
  GitHubUsername:
    Type: String
    Description: Which branch to use.
  GitHubRepoName:
    Type: String
    Description: Which branch to use.
    Default: aws-swim-ingest-poc
  GitHubBranchName:
    Type: String
    Description: Which branch to use.
    Default: master
  GitHubToken:
    Type: String
    Description: Which branch to use.
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  IamRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-swim-ingest-poc-pipeline/53b561c3da901a0ef12d5b743796711d.template
      Parameters:
        ArtifactBucketName:
          Ref: ArtifactBucket
  ECRRepository:
    Type: AWS::ECR::Repository
  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-swim-ingest-poc-pipeline/cbf275bf2d758881b48edbb6b621e953.template
      Parameters:
        ArtifactBucketName:
          Ref: ArtifactBucket
        ECRRepositoryUri:
          Fn::Sub: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}
        CodePipelineServiceRoleArn:
          Fn::GetAtt:
          - IamRoles
          - Outputs.CodePipelineServiceRoleArn
        CodeBuildServiceRoleArn:
          Fn::GetAtt:
          - IamRoles
          - Outputs.CodeBuildServiceRoleArn
        GitHubUsername:
          Ref: GitHubUsername
        GitHubRepoName:
          Ref: GitHubRepoName
        GitHubBranchName:
          Ref: GitHubBranchName
        GitHubToken:
          Ref: GitHubToken
Outputs:
  ArtifactBucketName:
    Value:
      Ref: ArtifactBucket
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ArtifactBucketName
  ECRRepositoryUri:
    Value:
      Fn::Sub: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ECRRepositoryName
